# Site settings
title: Investir en mode IA
email: abdoulaye.doucoure@dauphine.eu
url: https://www.paypal.com/ncp/payment/TUT2PSSCBDPQ4
description: "Quels sont les avantages d'utiliser l'IA conversationnelle pour lever des fonds ? Le guide pratique pour lever des fonds efficacement grâce à l'intelligence artificielle conversationnelle."
keywords: "intelligence artificielle, investissement, levée de fonds, IA conversationnelle, entrepreneuriat, relations investisseurs, IA, technologie, finance, startups, levée de fonds, financement, startups, capital-risque, crowdfunding, IA accessible, entrepreneuriat féminin, IA responsable, éthique, impact social, livre, intelligence artificielle, investissement, précommande, offre spéciale, auteur, entrepreneur, investisseur, IA, technologie, éditeur, maison d'édition, intelligence artificielle, investissement, startups, produits dérivés, mode, IA, investissement, entrepreneuriat"
skills: "Les Relations Investisseurs assistées par l'IA"
meta_author: DOUCOURE Abdoulaye

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 1fa3c5 #18bc9c 80B3FF
  primary-rgb: "191,97,122" #24,288,156" "128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 201d39 #233140 A2122F

# Footer settings
footer:
  copyright: Abdoulaye DOUCOURE
  location: Emplacement #Location
  social: Autour du Web #Around the Web
  credits: Crédits #Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/neohack22
  - title: facebook
    url: https://www.facebook.com/ethercourt
  - title: linkedin
    url: https://www.linkedin.com/company/ethercourt/?viewAsMember=true
  - title: instagram
    url: https://www.instagram.com/neohack22_lyricaption/
  - title: github
    url: https://github.com/neohack22/ai-powered-fundraising/

# Postal address (add as many lines as necessary)
address:
  - line: PAR
  - line: BKO

# Credits content
credits: 'Investir en mode IA est édité par <a href="https://ethercourt.github.io/strategies/">Ethercourt Machine Learning</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
